In [1]:
#引入pandas库
import pandas as pd

In [2]:
orders_raw = pd.read_csv('orders.csv')
orders_raw.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,order_date
0,2539329,1,prior,1,2,8,-1.0,20160105
1,2398795,1,prior,2,3,7,15.0,20160120
2,473747,1,prior,3,3,12,21.0,20160210
3,2254736,1,prior,4,4,7,29.0,20160310
4,431534,1,prior,5,4,15,28.0,20160407

In [3]:
orders=orders_raw.drop(['order_id','eval_set','order_number'],axis=1)
orders.head()

   user_id  order_dow  order_hour_of_day  days_since_prior_order  order_date
0        1          2                  8                    -1.0    20160105
1        1          3                  7                    15.0    20160120
2        1          3                 12                    21.0    20160210
3        1          4                  7                    29.0    20160310
4        1          4                 15                    28.0    20160407

In [4]:
orders.groupby('order_date').mean()

,user_id,order_dow,order_hour_of_day,days_since_prior_order
order_date,,,,
20160101,96978.879258,5.0,13.380474,10.406478
20160102,96736.977418,6.0,13.476399,10.119610
20160103,97251.137812,7.0,13.501724,10.203752
20160104,96996.585515,1.0,13.380465,10.304319
20160105,96087.394428,2.0,13.435186,10.355604
20160106,96969.276070,3.0,13.508379,10.303677
20160107,97332.306520,4.0,13.475594,10.244510
20160108,95802.356816,5.0,13.516948,10.200510
20160109,96691.796986,6.0,13.466015,10.228466
20160110,96560.028065,7.0,13.512823,10.272912
20160111,96745.964693,1.0,13.420443,10.266889
20160112,97704.052758,2.0,13.389537,10.087069
20160113,96832.173898,3.0,13.427499,10.357371
20160114,97147.499791,4.0,13.395800,10.259265
20160115,96405.398664,5.0,13.478193,10.286523
20160116,96757.139446,6.0,13.455240,10.337799
20160117,97708.751201,7.0,13.386043,10.186072
20160118,96511.433652,1.0,13.453121,10.312623
20160119,96488.843346,2.0,13.480112,10.172252
20160120,97220.032027,3.0,13.405581,10.255282
20160121,96732.948108,4.0,13.443296,10.300234
20160122,96892.119616,5.0,13.415949,10.268090
20160123,97181.809700,6.0,13.444519,10.182894
20160124,96319.992455,7.0,13.394754,10.290523
20160125,96781.517391,1.0,13.453130,10.251454
20160126,96939.722204,2.0,13.452852,10.191555
20160127,96666.593726,3.0,13.412308,10.230673
20160128,97260.216617,4.0,13.441488,10.343687
20160129,96435.540766,5.0,13.456994,10.147278
20160130,96398.288139,6.0,13.465979,10.249837
...,...,...,...,...
20161231,95087.433404,6.0,13.280479,10.157858
20170101,97991.126133,7.0,13.466767,9.961480
20170102,95403.924303,1.0,13.516335,10.474104
20170103,98140.207692,2.0,13.631624,10.121368
20170104,95380.742760,3.0,13.616695,10.683135
20170105,98567.469524,4.0,13.371429,9.678095
20170106,94533.022352,5.0,13.448008,10.442177
20170107,95510.378741,6.0,13.235294,10.509804
20170108,95466.693168,7.0,13.337888,9.752795
20170109,97330.735187,1.0,13.438936,10.250302
20170110,96760.757660,2.0,13.427577,10.520891
20170111,98654.491366,3.0,13.237049,10.076923
20170112,92798.000000,4.0,13.264610,9.936688
20170113,96473.339823,5.0,13.207080,10.513274
20170114,96613.408730,6.0,13.422619,10.698413
20170115,96176.492569,7.0,13.405520,10.216561
20170116,96971.799486,1.0,13.365039,9.678663
20170117,96667.195652,2.0,13.242236,10.739130
20170118,101577.887719,3.0,12.954386,10.052632
20170119,108207.502110,4.0,13.434599,11.016878
20170120,96640.661836,5.0,13.106280,8.884058
20170121,93194.285714,6.0,13.325714,9.194286
20170122,96337.277778,7.0,13.547619,11.468254
20170123,106740.755556,1.0,14.666667,9.988889
20170124,95421.241379,2.0,13.896552,10.000000
20170125,99947.113208,3.0,12.547170,11.886792
20170126,113765.100000,4.0,14.200000,11.750000
20170127,92899.066667,5.0,12.400000,13.866667
20170128,126062.333333,6.0,16.333333,11.333333
20170129,54844.000000,7.0,10.000000,2.000000

In [5]:
#根据order_date来排序
orders = orders.sort_values('order_date', inplace=False)
orders

,user_id,order_dow,order_hour_of_day,days_since_prior_order,order_date
3058067,188506,5,16,10.0,20160101
2443702,150384,5,9,-1.0,20160101
2443344,150361,5,10,6.0,20160101
1604966,98519,5,19,3.0,20160101
2442300,150307,5,10,7.0,20160101
2442093,150299,5,14,12.0,20160101
2441829,150285,5,13,3.0,20160101
1604767,98514,5,16,1.0,20160101
1605659,98548,5,20,7.0,20160101
2440578,150208,5,10,-1.0,20160101
520720,32099,5,13,1.0,20160101
520822,32104,5,10,9.0,20160101
1139499,70011,5,16,2.0,20160101
1139498,70011,5,8,4.0,20160101
1605911,98564,5,16,19.0,20160101
2440611,150211,5,16,7.0,20160101
2443991,150399,5,12,20.0,20160101
1604583,98503,5,15,6.0,20160101
517864,31934,5,12,13.0,20160101
2447398,150639,5,15,17.0,20160101
1602817,98373,5,14,30.0,20160101
1602829,98374,5,14,30.0,20160101
515629,31783,5,18,8.0,20160101
515667,31786,5,9,27.0,20160101
2447031,150614,5,10,7.0,20160101
516003,31802,5,16,15.0,20160101
516034,31804,5,13,3.0,20160101
2446414,150575,5,18,17.0,20160101
516596,31832,5,9,8.0,20160101
516834,31850,5,17,3.0,20160101
...,...,...,...,...,...
1767088,108495,4,9,3.0,20170126
1753970,107698,4,12,-1.0,20170126
2838825,175147,4,17,13.0,20170126
2322856,142944,4,17,6.0,20170126
2570186,158213,4,15,3.0,20170126
1687257,103555,4,11,8.0,20170126
3091910,190592,4,19,2.0,20170126
1490264,91550,4,14,30.0,20170126
2561422,157667,4,16,2.0,20170126
1366110,83945,4,17,7.0,20170126
1336325,82110,4,16,4.0,20170126
2331763,143458,5,14,-1.0,20170127
2862793,176595,5,14,30.0,20170127
1463923,89935,5,16,30.0,20170127
1689415,103671,5,7,0.0,20170127
2825468,174318,5,11,9.0,20170127
2540452,156369,5,12,7.0,20170127
2455855,151169,5,16,16.0,20170127
2062938,126844,5,11,30.0,20170127
2093558,128735,5,16,5.0,20170127
34704,2211,5,11,4.0,20170127
836507,51391,5,15,23.0,20170127
1888,133,5,3,8.0,20170127
158830,9783,5,17,30.0,20170127
968218,59498,5,13,3.0,20170127
313025,19376,5,10,14.0,20170127
2346707,144378,6,16,27.0,20170128
1712042,105074,6,21,5.0,20170128
2093559,128735,6,12,2.0,20170128
893446,54844,7,10,2.0,20170129

In [6]:
#根据时间将product_count进行合并
product_count_sum = orders.groupby('order_date').sum()
product_count_sum

               user_id  order_dow  order_hour_of_day  days_since_prior_order
order_date
20160101     637733110      32880              87990                 68433.0
20160102     664002613      41184              92502                 69461.0
20160103     704973498      50743              97874                 73967.0
20160104     729899306       7525             100688                 77540.0
20160105     744965569      15506             104163                 80287.0
20160106     804360145      24885             112052                 85469.0
20160107     855453642      35156             118437                 90039.0
20160108     901595980      47055             127208                 95997.0
20160109     968755114      60114             134916                102479.0
20160110     997754770      72331             139628                106150.0
20160111    1043985705      10791             144820                110790.0
20160112    1096337176      22442             150244                113187.0
20160113    1122575392      34779             155665                120073.0
20160114    1161204065      47812             160120                122629.0
20160115    1226758698      63625             171510                130896.0
20160116    1292675383      80160             179762                138113.0
20160117    1342713659      96194             183951                139977.0
20160118    1373164678      14228             191411                146728.0
20160119    1416649198      29364             197915                149349.0
20160120    1463161482      45150             201754                154342.0
20160121    1487559276      61512             206731                158397.0
20160122    1574690728      81260             218036                166877.0
20160123    1600973133      98844             221485                167753.0
20160124    1659689790     120617             230805                177316.0
20160125    1697354252      17538             235941                179790.0
20160126    1733282233      35760             240537                182225.0
20160127    1778085325      55182             246706                188183.0
20160128    1791046889      73660             247525                190479.0
20160129    1851080205      95975             258307                194777.0
20160130    1925363009     119838             268956                204720.0
...                ...        ...                ...                     ...
20161231     134929068       8514              18845                 14414.0
20170101     129740251       9268              17830                 13189.0
20170102     119731925       1255              16963                 13145.0
20170103     114824043       2340              15949                 11842.0
20170104     111976992       3522              15986                 12542.0
20170105     103495843       4200              14040                 10162.0
20170106      97274480       5145              13838                 10745.0
20170107      92549557       5814              12825                 10184.0
20170108      76850688       5635              10737                  7851.0
20170109      80492518        827              11114                  8477.0
20170110      69474224       1436               9641                  7554.0
20170111      62842911       1911               8432                  6419.0
20170112      57163568       2464               8171                  6121.0
20170113      54507437       2825               7462                  5940.0
20170114      48693158       3024               6765                  5392.0
20170115      45299128       3297               6314                  4812.0
20170116      37722030        389               5199                  3765.0
20170117      31126837        644               4264                  3458.0
20170118      28949698        855               3692                  2865.0
20170119      25645178        948               3184                  2611.0
20170120      20004617       1035               2713                  1839.0
20170121      16309000       1050               2332                  1609.0
20170122      12138497        882               1707                  1445.0
20170123       9606668         90               1320                   899.0
20170124       5534432        116                806                   580.0
20170125       5297197        159                665                   630.0
20170126       2275302         80                284                   235.0
20170127       1393486         75                186                   208.0
20170128        378187         18                 49                    34.0
20170129         54844          7                 10                     2.0

[395 rows x 4 columns]

In [7]:
len(product_count_sum)

395

In [8]:
# pc_sum =[]
# od_record = 20160101 
# sum = 0
# for pc , od in zip(orders['product_count'], orders['order_date']):  
#     if od == od_record:
#         sum = sum + pc
#     else:
#         pc_sum.append(sum)
#         sum = 0
#     od_record = od
# pc_sum

In [9]:
dow =[5]
od_record = 5
for orders_dow in orders['order_dow']:  
    if orders_dow == od_record:
        continue
    else:
        dow.append(orders_dow)
    od_record = orders_dow
dow

[5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7]

In [10]:
len(dow)

395

In [11]:
#将dow赋给表中的order_dow
product_count_sum['order_dow']=dow
product_count_sum

               user_id  order_dow  order_hour_of_day  days_since_prior_order
order_date
20160101     637733110          5              87990                 68433.0
20160102     664002613          6              92502                 69461.0
20160103     704973498          7              97874                 73967.0
20160104     729899306          1             100688                 77540.0
20160105     744965569          2             104163                 80287.0
20160106     804360145          3             112052                 85469.0
20160107     855453642          4             118437                 90039.0
20160108     901595980          5             127208                 95997.0
20160109     968755114          6             134916                102479.0
20160110     997754770          7             139628                106150.0
20160111    1043985705          1             144820                110790.0
20160112    1096337176          2             150244                113187.0
20160113    1122575392          3             155665                120073.0
20160114    1161204065          4             160120                122629.0
20160115    1226758698          5             171510                130896.0
20160116    1292675383          6             179762                138113.0
20160117    1342713659          7             183951                139977.0
20160118    1373164678          1             191411                146728.0
20160119    1416649198          2             197915                149349.0
20160120    1463161482          3             201754                154342.0
20160121    1487559276          4             206731                158397.0
20160122    1574690728          5             218036                166877.0
20160123    1600973133          6             221485                167753.0
20160124    1659689790          7             230805                177316.0
20160125    1697354252          1             235941                179790.0
20160126    1733282233          2             240537                182225.0
20160127    1778085325          3             246706                188183.0
20160128    1791046889          4             247525                190479.0
20160129    1851080205          5             258307                194777.0
20160130    1925363009          6             268956                204720.0
...                ...        ...                ...                     ...
20161231     134929068          6              18845                 14414.0
20170101     129740251          7              17830                 13189.0
20170102     119731925          1              16963                 13145.0
20170103     114824043          2              15949                 11842.0
20170104     111976992          3              15986                 12542.0
20170105     103495843          4              14040                 10162.0
20170106      97274480          5              13838                 10745.0
20170107      92549557          6              12825                 10184.0
20170108      76850688          7              10737                  7851.0
20170109      80492518          1              11114                  8477.0
20170110      69474224          2               9641                  7554.0
20170111      62842911          3               8432                  6419.0
20170112      57163568          4               8171                  6121.0
20170113      54507437          5               7462                  5940.0
20170114      48693158          6               6765                  5392.0
20170115      45299128          7               6314                  4812.0
20170116      37722030          1               5199                  3765.0
20170117      31126837          2               4264                  3458.0
20170118      28949698          3               3692                  2865.0
20170119      25645178          4               3184                  2611.0
20170120      20004617          5               2713                  1839.0
20170121      16309000          6               2332                  1609.0
20170122      12138497          7               1707                  1445.0
20170123       9606668          1               1320                   899.0
20170124       5534432          2                806                   580.0
20170125       5297197          3                665                   630.0
20170126       2275302          4                284                   235.0
20170127       1393486          5                186                   208.0
20170128        378187          6                 49                    34.0
20170129         54844          7                 10                     2.0

[395 rows x 4 columns]

In [12]:
# date =[20160101]
# date_record = 20160101
# for orders_date in orders['order_date']:  
#     if orders_date == date_record:
#         continue
#     else:
#         date.append(orders_date)
#     date_record = orders_date
# date

In [13]:
# len(date)

In [14]:
orders_final=product_count_sum.drop(['user_id','order_hour_of_day','days_since_prior_order'],axis=1)
orders_final

            order_dow
order_date
20160101            5
20160102            6
20160103            7
20160104            1
20160105            2
20160106            3
20160107            4
20160108            5
20160109            6
20160110            7
20160111            1
20160112            2
20160113            3
20160114            4
20160115            5
20160116            6
20160117            7
20160118            1
20160119            2
20160120            3
20160121            4
20160122            5
20160123            6
20160124            7
20160125            1
20160126            2
20160127            3
20160128            4
20160129            5
20160130            6
...               ...
20161231            6
20170101            7
20170102            1
20170103            2
20170104            3
20170105            4
20170106            5
20170107            6
20170108            7
20170109            1
20170110            2
20170111            3
20170112            4
20170113            5
20170114            6
20170115            7
20170116            1
20170117            2
20170118            3
20170119            4
20170120            5
20170121            6
20170122            7
20170123            1
20170124            2
20170125            3
20170126            4
20170127            5
20170128            6
20170129            7

[395 rows x 1 columns]

In [15]:
# X=orders_final.drop(['order_dow'],axis=1)
# Y=orders_final['order_dow']
# Y=orders_final['product_count']

In [16]:
orders_again = orders[:370]
orders_again

,user_id,order_dow,order_hour_of_day,days_since_prior_order,order_date
3058067,188506,5,16,10.0,20160101
2443702,150384,5,9,-1.0,20160101
2443344,150361,5,10,6.0,20160101
1604966,98519,5,19,3.0,20160101
2442300,150307,5,10,7.0,20160101
2442093,150299,5,14,12.0,20160101
2441829,150285,5,13,3.0,20160101
1604767,98514,5,16,1.0,20160101
1605659,98548,5,20,7.0,20160101
2440578,150208,5,10,-1.0,20160101
520720,32099,5,13,1.0,20160101
520822,32104,5,10,9.0,20160101
1139499,70011,5,16,2.0,20160101
1139498,70011,5,8,4.0,20160101
1605911,98564,5,16,19.0,20160101
2440611,150211,5,16,7.0,20160101
2443991,150399,5,12,20.0,20160101
1604583,98503,5,15,6.0,20160101
517864,31934,5,12,13.0,20160101
2447398,150639,5,15,17.0,20160101
1602817,98373,5,14,30.0,20160101
1602829,98374,5,14,30.0,20160101
515629,31783,5,18,8.0,20160101
515667,31786,5,9,27.0,20160101
2447031,150614,5,10,7.0,20160101
516003,31802,5,16,15.0,20160101
516034,31804,5,13,3.0,20160101
2446414,150575,5,18,17.0,20160101
516596,31832,5,9,8.0,20160101
516834,31850,5,17,3.0,20160101
...,...,...,...,...,...
484432,29898,5,10,16.0,20160101
2487705,153031,5,18,25.0,20160101
1586798,97415,5,11,7.0,20160101
487496,30056,5,9,2.0,20160101
487511,30056,5,13,4.0,20160101
2483809,152806,5,12,4.0,20160101
2483215,152778,5,12,30.0,20160101
2483024,152764,5,8,7.0,20160101
1587286,97437,5,13,3.0,20160101
2482854,152756,5,19,13.0,20160101
488758,30134,5,10,14.0,20160101
2482107,152696,5,17,30.0,20160101
2482056,152693,5,16,10.0,20160101
489050,30147,5,15,21.0,20160101
1587494,97449,5,18,30.0,20160101
489195,30154,5,19,4.0,20160101
2481276,152647,5,12,12.0,20160101
2484283,152834,5,16,7.0,20160101
2487868,153043,5,12,20.0,20160101
1586670,97408,5,21,10.0,20160101
3128494,192840,5,15,10.0,20160101
2487165,153001,5,21,24.0,20160101
2487147,153000,5,14,4.0,20160101
485186,29936,5,16,1.0,20160101
2486883,152984,5,11,14.0,20160101
1585850,97350,5,11,19.0,20160101
485571,29960,5,9,12.0,20160101
1585969,97362,5,12,7.0,20160101
2486409,152965,5,11,6.0,20160101
2486317,152962,5,14,30.0,20160101

In [17]:
X=orders_again.drop(['product_count'],axis=1)
Y=orders_again['product_count']

KeyError: "['product_count'] not found in axis"

In [ ]:
# from sklearn.decomposition import PCA
# transfer = PCA(n_components=0.90)
# xT = transfer.fit_transform(X)

In [ ]:
# split the train data and test data using train_test_split()
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=22)

In [ ]:
# # Standard the data using standardScalar
# from sklearn.preprocessing import StandardScaler
# transfer = StandardScaler()
# x_train = transfer.fit_transform(x_train)
# x_test = transfer.transform(x_test)

In [ ]:
# I use random forest algorithm to predict the results
# Import the RandomForestClassifier & GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, SGDRegressor

In [ ]:
estimator = LinearRegression()
estimator.fit(x_train, y_train)

In [ ]:
print("xishu", estimator.coef_)
print(estimator.intercept_)

In [ ]:
y_predict = estimator.predict(x_test)

In [ ]:
print(y_predict)

In [ ]:
print(x_test)

In [ ]:
# 确定x_x里面的值只有orderdow就行
import numpy as np
x_x=x_test['order_dow']
x_x = np.array(x_x)
x_x

In [ ]:
# print(y_predict > y_test-1 && y_predict < y_test+1)

In [ ]:
# print(y_predict<y_test+100 && y>y_test-100)

In [ ]:
# error = mean_squared_error(y_test, y_predict)

In [ ]:
score = estimator.score(x_test, y_test)
score

In [ ]:
import numpy as np
MSE = np.square(np.subtract(y_test,y_predict)).mean()
MSE

In [ ]:
from sklearn.metrics import mean_squared_error 
mean_squared_error(y_predict,y_test)

In [ ]:
# print("The Root Mean Squared Error (RMSE) is:", np.sqrt(metrics.mean_squared_error(y_test, target_pred)))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from matplotlib.lines import Line2D

In [ ]:
type(y_predict)

In [ ]:
bar_table = pd.DataFrame({
    'order_dow':x_x,
    'product_prediction':y_predict
})
bar_table

In [ ]:
bar_y_choose_prepare = bar_table.groupby('order_dow').sum()
bar_y_choose_prepare

In [ ]:
y_lable_value=bar_y_choose_prepare['product_prediction']
y_lable_value

In [ ]:
x_label_value=[1,2,3,4,5,6,7]
x_label_value

In [ ]:
# num_dows = orders["order_dow"].max() - orders["order_dow"].min() + 1
# plt.hist(orders["order_dow"], bins=y_predict, edgecolor="black")
plt.bar(x_label_value, y_lable_value, fc='b')
plt.title("Product Count Prediction")
# plt.xlabel("weekday")
# plt.ylabel("product_count")
ply.show()